### ISSUE TITLE
RC4 roadmap

### ISSUE THREAD

**Issue by psanders** [fonoster/routr#46]
The areas of focus for RC4 are:

- [x] Freeze changes in the public API(`apiVersion == v1beta1`)
- [x] Replace the testing tool with Mocha and Istanbul to allow for test coverage
- [x] Bring [`GraalJS`](https://www.graalvm.org) as the default JS engine
- [x] Re-write the `Location` module to improve performance
- [x] Review the architecture to allow for better decoupling and scalability
- [x] Work on bringing the server to the following platforms:
    - [x] Ubuntu Snaps
    - [x] DigitalOcean droplet
    - [x] Docker
    - [x] Kubernetes
    - [x] Google Cloud Shell
    - [x] Custom
- [x] Bring the [`routr-ui`](https://github.com/fonoster/routr-ui) to a beta version
- [x] Add experimental support for IPv6

**Comment by moggle-mog** [comment]
For more scalability, I have one additional idea:
Try to make `location` store in external database such as redis so that you can make your work stateless.

**Comment by psanders** [comment]
@moggle-mog 

I'm glad you say that. I'm looking at different ways to delegate as much as possible the state of the application. As you point, one option is using a database like Redis. Another option could be using a Distributed Hash Tables, but I have yet to find a good implementation for my use case.

Perhaps I have to experiment with both options and see which one yields better performance.

**Comment by moggle-mog** [comment]
I am looking forward to your work!

**Comment by psanders** [comment]
I was able to run a proof of concept in a IPv6-only network. I created a setup with Routr, Jitsi, and Linphone and it work in RC4. I started to update the ACL module to support IPv6 address. A lot more work is needed before is of any use, but is a good start.

**Comment by psanders** [comment]
RC4 is all task complete. We are now in the testing phase!

**Comment by psanders** [comment]
RC4 is finally out! 🎉
